# conda env create --file environment.yml
name: venv_ml_pro
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - pathlib
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.10
  - seaborn
  - scipy
  - scikit-learn
  - pip
  - pyprojroot
  - python=3.10
  - joblib
  - pip:
    - pyhere
    